/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

Tables Used:
    - gold_dim_customers
    - gold_dim_products
    - gold_fact_sales

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total number of customers by country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM
    gold_dim_customers
GROUP BY
    country
ORDER BY
    total_customers DESC;

-- Find total number of customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM
    gold_dim_customers
GROUP BY
    gender
ORDER BY
    total_customers DESC;

-- Find total number of products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM
    gold_dim_products
GROUP BY
    category
ORDER BY
    total_products DESC;

-- Find average cost per category
SELECT
    category,
    AVG(cost) AS avg_cost
FROM
    gold_dim_products
GROUP BY
    category
ORDER BY
    avg_cost DESC;

-- Find total revenue generated for each product category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM
    gold_fact_sales f
    LEFT JOIN gold_dim_products p ON p.product_key = f.product_key
GROUP BY
    p.category
ORDER BY
    total_revenue DESC;

-- Find total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM
    gold_fact_sales f
    LEFT JOIN gold_dim_customers c ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY
    total_revenue DESC;

-- Find total number of items sold across countries
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM
    gold_fact_sales f
    LEFT JOIN gold_dim_customers c ON c.customer_key = f.customer_key
GROUP BY
    c.country
ORDER BY
    total_sold_items DESC;
